// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVtzQu7pq8WDLnPpPYI9IDLUQlTWTMts',
    appId: '1:445971805919:web:09fd6a49acd735d2551b6a',
    messagingSenderId: '445971805919',
    projectId: 'test-login-1f919',
    authDomain: 'test-login-1f919.firebaseapp.com',
    storageBucket: 'test-login-1f919.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZh6_ZbMpzvgEecimxwFWoyO3kOUPICdE',
    appId: '1:445971805919:android:a631510e3a0683ed551b6a',
    messagingSenderId: '445971805919',
    projectId: 'test-login-1f919',
    storageBucket: 'test-login-1f919.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWS3jNp8Li0TCM_DSqMoMvJxPEltUya5M',
    appId: '1:445971805919:ios:6e5ca74521d429a6551b6a',
    messagingSenderId: '445971805919',
    projectId: 'test-login-1f919',
    storageBucket: 'test-login-1f919.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWS3jNp8Li0TCM_DSqMoMvJxPEltUya5M',
    appId: '1:445971805919:ios:6e5ca74521d429a6551b6a',
    messagingSenderId: '445971805919',
    projectId: 'test-login-1f919',
    storageBucket: 'test-login-1f919.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkVtzQu7pq8WDLnPpPYI9IDLUQlTWTMts',
    appId: '1:445971805919:web:74f532172abf09cf551b6a',
    messagingSenderId: '445971805919',
    projectId: 'test-login-1f919',
    authDomain: 'test-login-1f919.firebaseapp.com',
    storageBucket: 'test-login-1f919.firebasestorage.app',
  );

}